### ISSUE TITLE
SslStreamX.SyncData method UnhandledException

### ISSUE THREAD

**Issue by IKende** [IKende/BeetleX#17]
Create buffer error, maximum number of buffer pools!
   at BeetleX.Buffers.BufferPool.CreateBuffer()
   at BeetleX.Buffers.BufferPool.Pop()
   at BeetleX.Buffers.SslStreamX.SyncData()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by IKende** [comment]
fix v1.2.7.2
