### ISSUE TITLE
PipeStream添加Write char和Write StringBuilder方法

### ISSUE THREAD

**Issue by IKende** [IKende/BeetleX#40]
PipeStream添加Write(char[] data,int offset,int count)和Write(StringBuilder data)

**Comment by IKende** [comment]
``` csharp 
       public bool TryReadLine(out CharBlock value, Encoding encoding, bool returnEof = false)

        public bool TryReadWith(byte[] eof, out CharBlock value, Encoding encoding, bool returnEof = false)
    
        public ByteBlock ReadBytes(int length)
        
        public CharBlock ReadChars(int length, Encoding encoding = null)
      
        public int ReadChars(char[] data, int length, Encoding encoding = null)
     
        public void Write(ArraySegment<char> data, Encoding encoding = null)
      
        public void Write(char[] data, int offset, int cout, Encoding encoding = null)
       
        public void Write(StringBuilder data, Encoding encoding = null)
```

**Comment by liyuan0420** [comment]
![150902_f361edb6_5617908](https://user-images.githubusercontent.com/45351609/72240629-acd8d900-361f-11ea-9258-17286343c181.png)

**Comment by liyuan0420** [comment]
SpanJson.JsonSerializer.NonGeneric.Utf8.SerializeToArrayPool(data)
报错：
Operation is not valid due to the current state of the object
堆栈：
at lambda_method(Closure , JsonWriter1& , MsgType ) at SpanJson.Formatters.EnumStringFormatter3.Serialize(JsonWriter1& writer, T value) in C:\projects\spanjson\SpanJson\Formatters\EnumStringFormatter.cs:line 23 at lambda_method(Closure , JsonWriter1& , MessageContent )
at SpanJson.Formatters.ComplexClassFormatter3.Serialize(JsonWriter1& writer, T value) in C:\projects\spanjson\SpanJson\Formatters\ComplexClassFormatter.cs:line 32
at lambda_method(Closure , Object )
at SpanJson.JsonSerializer.NonGeneric.Inner`2.InnerSerializeToByteArrayPool(Object input) in C:\projects\spanjson\SpanJson\JsonSerializer.NonGeneric.cs:line 68
at SpanJson.JsonSerializer.NonGeneric.Utf8.SerializeToArrayPool(Object input) in C:\projects\spanjson\SpanJson\JsonSerializer.NonGeneric.cs:line 485
at BeetleXServer.Models.JsonPacket.OnWrite(ISession session, Object data, PipeStream stream) in L:\VSDemo\NetCoreBeetleXServer\BeetleXServer\BeetleXServer\Models\JsonPacket.cs:line 40
at BeetleX.Packets.FixedHeaderPacket.OnEncode(ISession session, Object data, Stream stream)
at BeetleX.Packets.FixedHeaderPacket.Encode(Object data, ISession session, Stream stream)
at BeetleX.TcpSession.WriterData(Object data, Stream stream)
at BeetleX.TcpSession.ProcessSendMessages()
at BeetleX.TcpSession.Send(Object data)
at BeetleX.TcpServer.Send(Object data, ISession session)

**Comment by IKende** [comment]
update to 1.4.8.6
