### ISSUE TITLE
Operation is not valid due to the current state of the object

### ISSUE THREAD

**Issue by liyuan0420** [IKende/BeetleX#41]
SpanJson.JsonSerializer.NonGeneric.Utf8.SerializeToArrayPool(data)
报错：
Operation is not valid due to the current state of the object
堆栈：
at lambda_method(Closure , JsonWriter1& , MsgType ) at SpanJson.Formatters.EnumStringFormatter3.Serialize(JsonWriter1& writer, T value) in C:\projects\spanjson\SpanJson\Formatters\EnumStringFormatter.cs:line 23 at lambda_method(Closure , JsonWriter1& , MessageContent )
at SpanJson.Formatters.ComplexClassFormatter3.Serialize(JsonWriter1& writer, T value) in C:\projects\spanjson\SpanJson\Formatters\ComplexClassFormatter.cs:line 32
at lambda_method(Closure , Object )
at SpanJson.JsonSerializer.NonGeneric.Inner`2.InnerSerializeToByteArrayPool(Object input) in C:\projects\spanjson\SpanJson\JsonSerializer.NonGeneric.cs:line 68
at SpanJson.JsonSerializer.NonGeneric.Utf8.SerializeToArrayPool(Object input) in C:\projects\spanjson\SpanJson\JsonSerializer.NonGeneric.cs:line 485
at BeetleXServer.Models.JsonPacket.OnWrite(ISession session, Object data, PipeStream stream) in L:\VSDemo\NetCoreBeetleXServer\BeetleXServer\BeetleXServer\Models\JsonPacket.cs:line 40
at BeetleX.Packets.FixedHeaderPacket.OnEncode(ISession session, Object data, Stream stream)
at BeetleX.Packets.FixedHeaderPacket.Encode(Object data, ISession session, Stream stream)
at BeetleX.TcpSession.WriterData(Object data, Stream stream)
at BeetleX.TcpSession.ProcessSendMessages()
at BeetleX.TcpSession.Send(Object data)
at BeetleX.TcpServer.Send(Object data, ISession session)

**Comment by IKende** [comment]
建议升级一下[SpanJson](https://github.com/Tornhoof/SpanJson),`SpanJson`建议不要处理匿名类，如果有需要最好更换成`Newtonsoft.Json`
