### ISSUE TITLE
Session SslStreamX.SyncData unhandled exception!

### ISSUE THREAD

**Issue by IKende** [IKende/BeetleX#57]
``` csharp
Object reference not set to an instance of an object.
   at BeetleX.TcpServer.SessionReceive(SessionReceiveEventArgs e)
   at BeetleX.TcpSession.InvokeReceiveEvent()
   at BeetleX.Buffers.SslStreamX.SyncData(Action receive)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by IKende** [comment]
v1.5.1.6 fixed
